[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "qse"
description = "Quantum Simulation Environment"
readme = "README.md"
authors = [
    {name = "Rajarshi Tiwari", email = "rajarshi.tiwari@ichec.ie"},
    {name = "James Nelson", email = "james.nelson@ichec.ie"},
    {name = "Sherry Blair", email = "sherry.blair@ichec.ie"},
    ]
dynamic = ["version"]
requires-python = ">=3.10"
dependencies = [
    "ase",
    "numpy",
    "matplotlib",
]

[project.urls]
homepage = "https://github.com/rajarshitiwari/qse"

[project.optional-dependencies]
pulser = ["pulser == 1.4.0"]
muqlm = ["numpy == 1.26.4", "myqlm == 1.11.3"]


[tool.mypy]
ignore_missing_imports = true
no_implicit_optional = false
enable_error_code = 'ignore-without-code'

[tool.isort]
profile = "black"