#!/bin/sh

# An example hook script to verify what is about to be pushed.  Called by "git
# push" after it has checked the remote status, but before anything has been
# pushed.  If this script exits with a non-zero status nothing will be pushed.
#
# This hook is called with the following parameters:
#
# $1 -- Name of the remote to which the push is being done
# $2 -- URL to which the push is being done
#
# If pushing without using a named remote those arguments will be equal.
#
# Information about the commits which are being pushed is supplied as lines to
# the standard input in the form:
#
#   <local ref> <local oid> <remote ref> <remote oid>
#
# This sample shows how to prevent push of commits where the log message starts
# with "WIP" (work in progress).

remote="$1"
url="$2"

zero=$(git hash-object --stdin </dev/null | tr '[0-9a-f]' '0')

while read local_ref local_oid remote_ref remote_oid
do
	if test "$local_oid" = "$zero"
	then
		# Handle delete
		:
	else
		if test "$remote_oid" = "$zero"
		then
			# New branch, examine all commits
			range="$local_oid"
		else
			# Update to existing branch, examine new commits
			range="$remote_oid..$local_oid"
		fi

		# Check for WIP commit
		commit=$(git rev-list -n 1 --grep '^WIP' "$range")
		if test -n "$commit"
		then
			echo >&2 "Found WIP commit in $local_ref, not pushing"
			exit 1
		fi
	fi
done

#!/bin/bash

echo "Running isort and black checks before push..."

isort . --check --diff
if [ $? -ne 0 ]; then
  echo "isort failed. Please fix the import order."
  exit 1
fi

black . --check --diff
if [ $? -ne 0 ]; then
  echo "black failed. Please format your code."
  exit 1
fi

flake8 qse
if [ $?  -ne 0 ]; then
  echo "flake8 failed. Please check the errors."
  exit 1
fi

version=`grep version pyproject.toml`
read -r major minor patch <<<$(echo $version|sed 's/=/\n/g'|tail -1|sed 's/"//g'|tr '.' ' ')
new_version="version = \"$major.$minor.$[patch+1]\""

echo "Incrementing patch number: old -> $version new -> $new_version"
echo "updating pyproject.toml"

sed -i '' -e "s/$version/$new_version/g" pyproject.toml

if [ $? -ne 0 ]; then
    echo "error updating patch number!"
    exit 1
fi

echo "All checks passed. Ready to push. committing pyproject change before push!"

git commit -m "changed $(grep version pyproject.toml)" pyproject.toml


exit 0
