r"""
A collection of convenience functions for creating common lattices.
Qbits class is very flexible to generate arbitrary structures. For
convenience, helper functions to generate several common types of
lattices is defined here. See the examples below -


.. jupyter-execute::

    import qse
    qsqr = qse.lattices.square(
        lattice_spacing=1.0,
        repeats_x=4, repeats_y=4)
    qsqr.draw(radius=2)

Generic Definition
------------------

Any arbitrary periodic structure is defined in terms of two
objects, :math:`(i)` a set of points that are chosen, and
:math:`(ii)` a set of linearly independent vectors, called
primitive lattice vectors, through which we translate the points.

For example, for 2D square lattice, one has just one point at
origin :math:`(0, 0)`, and two lattice vectors :math:`{\bf A_1} = (a, 0)`
and :math:`{\bf A_2} = (0, a)` with :math:`a` being the lattice spacing.

Then one translate the points at origin to all passible integer
linear combinations :math:`n_1 {\bf A_1} + n_2 {\bf A_2}`.

Mathematically a lattice is usually infinite, however we usually
work with finite repititions, so :math:`n_1, n_2` are bounded
by the extent or size of the pattern, which in the above example
is 4.

In 2D one needs 2 lattice vectors, and in 3D one need 3 lattice
vectors. A number of lattices can be generated by just one point,
and suitably choosing the lattice vectors.

More complex structure require multiple points to translate to,
in order to generate the desired structure.
"""

__all__ = [
    "chain",
    "hexagonal",
    "kagome",
    "ring",
    "square",
    "torus",
    "triangular",
]

from .lattices import (
    chain,
    hexagonal,
    kagome,
    ring,
    square,
    torus,
    triangular,
)
